apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kodemo
spec:
  template:
    metadata:
      # This is the name of our new "Revision," it must follow the convention {service-name}-{revision-name}
      name: kodemo-rev
    spec:
      containers:
        - image: github.com/AnalyticsTestDemo/Kodemo
          ports:
            - containerPort: 8080
